apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
  replicas: 1
  strategy: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
      - image: suportegm/backend:latest
        name: backend
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512M"
      restartPolicy: Always
status: {}
